import { NextRequest } from "next/server";
import { PDFDocument, StandardFonts, rgb, degrees, PDFFont } from "pdf-lib";
import { requireUser } from "@/lib/auth/require-user";

type WritingTopic = {
  id: string;
  year: number;
  month: number;
  day: number;
  question_en: string;
  question_zh: string | null;
  question_type: string | null;
  topic_category: string | null;
  created_at: string;
  updated_at: string;
};

type ExportPayload = {
  category: string;
  questionType: string;
};

const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const MARGIN_X = 50;
const MARGIN_TOP = 60;
const MARGIN_BOTTOM = 50;

const BODY_SIZE = 11;
const SMALL_SIZE = 9;
const TITLE_SIZE = 20;
const SUBTITLE_SIZE = 13;

const LINE_GAP = 4;

function sanitizeFilename(value: string) {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^\w\u4e00-\u9fff-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

function safePdfText(text: string | null | undefined) {
  if (!text) return "";
  return text
    .replace(/[•]/g, "-")
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/\u00A0/g, " ")
    .replace(/[^\x09\x0A\x0D\x20-\x7E]/g, "");
}

function wrapText(
  text: string,
  maxWidth: number,
  font: PDFFont,
  fontSize: number
): string[] {
  const cleaned = safePdfText(text);
  const paragraphs = cleaned.split("\n");
  const lines: string[] = [];

  for (const paragraph of paragraphs) {
    const p = paragraph.trim();

    if (!p) {
      lines.push("");
      continue;
    }

    const words = p.split(/\s+/);
    let current = "";

    for (const word of words) {
      const candidate = current ? `${current} ${word}` : word;
      const width = font.widthOfTextAtSize(candidate, fontSize);

      if (width <= maxWidth) {
        current = candidate;
      } else {
        if (current) lines.push(current);

        if (font.widthOfTextAtSize(word, fontSize) <= maxWidth) {
          current = word;
        } else {
          let chunk = "";

          for (const ch of word) {
            const test = chunk + ch;
            if (font.widthOfTextAtSize(test, fontSize) <= maxWidth) {
              chunk = test;
            } else {
              if (chunk) lines.push(chunk);
              chunk = ch;
            }
          }

          current = chunk;
        }
      }
    }

    if (current) lines.push(current);
  }

  return lines;
}

function toPdfResponseBuffer(bytes: Uint8Array) {
  return bytes.buffer.slice(
    bytes.byteOffset,
    bytes.byteOffset + bytes.byteLength
  ) as ArrayBuffer;
}

function formatDate(year: number, month: number, day: number) {
  const mm = String(month).padStart(2, "0");
  const dd = String(day).padStart(2, "0");
  return `${year}-${mm}-${dd}`;
}

function formatQuestionType(type: string | null) {
  if (!type) return "general";

  const map: Record<string, string> = {
    agree: "agree / disagree",
    discuss: "discuss both views",
    problem: "problem / solution",
    advantage: "advantages / disadvantages",
    double: "double question",
    mixed: "mixed",
  };

  return map[type] ?? type;
}

function addWatermarkAndFooter(
  pdfDoc: PDFDocument,
  font: PDFFont,
  boldFont: PDFFont
) {
  const pages = pdfDoc.getPages();
  const totalPages = pages.length;

  pages.forEach((page, index) => {
    const { width, height } = page.getSize();

    page.drawText("LOFTY EDUCATION", {
      x: width / 2 - 200,
      y: height / 2 - 170,
      size: 58,
      font: boldFont,
      color: rgb(0.85, 0.85, 0.85),
      rotate: degrees(45),
      opacity: 0.18,
    });

    page.drawText("Generated by Chi", {
      x: 40,
      y: 20,
      size: 9,
      font,
      color: rgb(0.55, 0.55, 0.55),
    });

    const pageLabel = `Page ${index + 1} of ${totalPages}`;
    const pageLabelWidth = font.widthOfTextAtSize(pageLabel, 9);

    page.drawText(pageLabel, {
      x: width - 40 - pageLabelWidth,
      y: 20,
      size: 9,
      font,
      color: rgb(0.55, 0.55, 0.55),
    });
  });
}

export async function POST(req: NextRequest) {
  try {
    const payload = (await req.json()) as ExportPayload;
    const { supabase } = await requireUser("/ielts/writing");

    let query = supabase
      .schema("ielts")
      .from("ielts_writing_topics")
      .select("*")
      .order("year", { ascending: false })
      .order("month", { ascending: false })
      .order("day", { ascending: false });

    if (payload.category !== "All") {
      query = query.eq("topic_category", payload.category);
    }

    if (payload.questionType !== "All") {
      query = query.eq("question_type", payload.questionType);
    }

    const { data, error } = await query;

    if (error) {
      return new Response(`Failed to load Writing data: ${error.message}`, {
        status: 500,
      });
    }

    const items = (data ?? []) as WritingTopic[];

    const pdfDoc = await PDFDocument.create();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    let page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    let y = PAGE_HEIGHT - MARGIN_TOP;

    const contentWidth = PAGE_WIDTH - MARGIN_X * 2;

    const ensureSpace = (neededHeight: number) => {
      if (y - neededHeight < MARGIN_BOTTOM) {
        page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
        y = PAGE_HEIGHT - MARGIN_TOP;
      }
    };

    const drawLine = (
      text: string,
      opts?: {
        size?: number;
        bold?: boolean;
        color?: [number, number, number];
      }
    ) => {
      const size = opts?.size ?? BODY_SIZE;
      const usedFont = opts?.bold ? boldFont : font;
      const color = opts?.color ?? [0, 0, 0];
      const lines = wrapText(text, contentWidth, usedFont, size);

      for (const line of lines) {
        ensureSpace(size + LINE_GAP);

        page.drawText(line || " ", {
          x: MARGIN_X,
          y,
          size,
          font: usedFont,
          color: rgb(color[0], color[1], color[2]),
        });

        y -= size + LINE_GAP;
      }
    };

    const addGap = (amount = 8) => {
      y -= amount;
    };

    drawLine("IELTS Writing Task 2", { size: TITLE_SIZE, bold: true });
    drawLine(`Category: ${safePdfText(payload.category) || "All"}`, {
      size: SUBTITLE_SIZE,
    });
    drawLine(`Question Type: ${safePdfText(payload.questionType) || "All"}`, {
      size: SUBTITLE_SIZE,
    });
    drawLine(`Total topics: ${items.length}`, { size: SMALL_SIZE });
    addGap(12);

    items.forEach((item, index) => {
      drawLine(`${index + 1}. ${safePdfText(item.question_en || "Untitled Topic")}`, {
        size: SUBTITLE_SIZE,
        bold: true,
      });

      drawLine(
        `Date: ${formatDate(item.year, item.month, item.day)}`,
        { size: SMALL_SIZE }
      );

      drawLine(
        `Topic: ${safePdfText(item.topic_category || "uncategorized")}`,
        { size: SMALL_SIZE }
      );

      drawLine(
        `Type: ${safePdfText(formatQuestionType(item.question_type))}`,
        { size: SMALL_SIZE }
      );

      addGap(4);

    //   drawLine("Essay Question", { size: SMALL_SIZE, bold: true });
    //   drawLine(item.question_en || "");
      addGap(5);

      if (item.question_zh && item.question_zh.trim() !== "") {
        drawLine("Chinese Translation", { size: SMALL_SIZE, bold: true });
        drawLine(item.question_zh);
        addGap(5);
      }

      addGap(10);
    });

    addWatermarkAndFooter(pdfDoc, font, boldFont);

    const pdfBytes = await pdfDoc.save();
    const pdfBuffer = toPdfResponseBuffer(pdfBytes);

    const filename = `writing-task2-${sanitizeFilename(
      payload.category || "all"
    )}-${sanitizeFilename(payload.questionType || "all")}.pdf`;

    return new Response(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${filename}"`,
      },
    });
  } catch (error) {
    console.error("Writing PDF export error:", error);
    return new Response("Failed to export PDF", { status: 500 });
  }
}