export type StaticRaPronunciationDrill = {
  id: string;
  title: string;
  question_text: string;
  focus: string;
  tags: string[];
};

const drill = (number: number, title: string, questionText: string, focus: string, group: string): StaticRaPronunciationDrill => ({
  id: `31000000-0000-4000-8000-${String(number).padStart(12, "0")}`,
  title,
  question_text: questionText,
  focus,
  tags: ["发音专项", group],
});

export const RA_PRONUNCIATION_DRILLS: StaticRaPronunciationDrill[] = [
  drill(1, "The Environment", "The impact of climate change can be observed across the entire planet. Scientists are examining the effect of rising temperatures on the oceans, the atmosphere, and the ecosystems that support human life. The evidence increasingly suggests that early action may reduce the economic and environmental costs of future climate-related disasters.", "the impact / the entire / the effect / the oceans / the atmosphere / the ecosystems / the evidence / the economic / environmental", "THE 变音"),
  drill(2, "Artificial Intelligence", "The introduction of artificial intelligence has transformed the way information is processed. The ability of modern systems to analyse enormous amounts of data allows organisations to identify patterns more efficiently. However, the ethical implications of automated decision-making remain an important area of academic and public debate.", "the introduction / the ability / the ethical / the important area / the academic", "THE 变音"),
  drill(3, "Education", "The aim of modern education is not simply to provide students with information. The emphasis has gradually shifted towards developing the ability to analyse evidence, evaluate arguments, and communicate ideas effectively. The overall objective is to prepare individuals for an increasingly complex social and professional environment.", "the aim / the emphasis / the ability / the overall / an increasingly", "THE 变音"),
  drill(4, "The Economy", "The economy is influenced by a wide range of domestic and international factors. The availability of employment, the expansion of industry, and the overall level of consumer confidence can affect economic growth. Understanding the interaction between these elements is therefore essential for effective economic policy.", "the economy / the availability / the expansion / the overall / the interaction / these elements / essential / effective", "THE 变音"),
  drill(5, "Energy", "The increasing demand for energy has encouraged governments to explore alternative sources of power. The use of renewable energy can reduce the environmental impact of electricity production, although the initial investment may be considerable. The effectiveness of these technologies will depend partly on improvements in energy storage.", "the increasing / the use / the environmental / the initial / the effectiveness / improvements / energy", "THE 变音"),
  drill(6, "Urban Development", "Rapid urban growth has created a number of challenges for modern cities. Local authorities must develop effective approaches to housing, public transport, and environmental protection. An important aspect of urban planning is ensuring that residents have easy access to essential services and employment opportunities.", "develop_effective / number_of / aspect_of / have_easy / access_to / employment_opportunities", "辅元连读"),
  drill(7, "Scientific Research", "Scientific research often involves a careful examination of existing evidence. Researchers may collect information from a variety of sources and analyse it using appropriate methods. An accurate interpretation of the results is essential if a study is expected to make a meaningful contribution to academic knowledge.", "research_often / examination_of / collect_information / variety_of / analyse_it / interpretation_of / is_essential / make_a", "辅元连读"),
  drill(8, "Public Health", "Public health experts often emphasise the importance of regular exercise and a balanced diet. Even a moderate increase in physical activity can have a positive effect on overall health. Individuals are therefore encouraged to adopt active lifestyles and avoid excessive consumption of highly processed food.", "experts_often / importance_of / Even_a / increase_in / have_a / effect_on / adopt_active / avoid_excessive", "辅元连读"),
  drill(9, "Technology", "Digital technology has become an essential part of everyday life. It allows individuals to access information almost instantly and communicate across enormous distances. At the same time, increased reliance on online services has raised important questions about privacy, security, and access to reliable information.", "become_an / part_of / access_information / across_enormous / reliance_on / raised_important / access_to", "辅元连读"),
  drill(10, "Academic Learning", "Effective academic learning requires more than memorising information. Students are expected to examine ideas critically, identify important evidence, and organise arguments in a logical manner. Developing these abilities can also improve performance in examinations and increase confidence in academic communication.", "examine_ideas / identify_important / arguments_in / abilities_can / in_examinations / confidence_in", "辅元连读"),
  drill(11, "Next Generation Technology", "The next generation of digital technology will create new opportunities for businesses and consumers. Rapid developments in artificial intelligence may also affect traditional employment patterns. Governments must therefore consider how best to prepare workers for jobs that may not yet exist.", "next generation / rapid developments / affect traditional / employment patterns / must therefore / best to", "失爆与吞音"),
  drill(12, "Environmental Protection", "Most people accept that environmental protection is important, but individual behaviour can be difficult to change. Governments have introduced different policies to encourage more sustainable choices. The best results are often achieved when public education is combined with practical economic incentives.", "most people / accept that / difficult to / introduced different / best results / public education", "失爆与吞音"),
  drill(13, "Food Production", "Modern food production depends on complex transport and distribution networks. Products must be moved quickly from farms and factories to shops and restaurants. Improved technology has reduced transport costs, but unexpected disruptions can still affect the availability of essential goods.", "depends on / transport and / products must / improved technology / transport costs / unexpected disruptions", "失爆与吞音"),
  drill(14, "Workplace Communication", "Effective communication is particularly important in fast-paced workplaces. Staff must understand instructions, report problems accurately, and respond quickly when unexpected situations occur. Good communication can prevent mistakes and help teams complete difficult tasks more efficiently.", "fast-paced / staff must / understand instructions / unexpected situations / prevent mistakes / difficult tasks", "失爆与吞音"),
  drill(15, "Climate Research", "Scientists have collected vast amounts of climate data over the past several decades. These records provide important information about changes in temperature, rainfall, and extreme weather events. The most significant patterns can only be identified when large datasets are examined over extended periods.", "vast amounts / past several / important information / most significant / datasets are / extended periods", "失爆与吞音"),
  drill(16, "Decision Making", "Would you make the same decision if you had access to additional information? Research suggests that people often change their judgement when new evidence becomes available. What you believe to be correct may therefore depend heavily on the information you receive and the way it is presented.", "would you / what you / information you / judgement when", "音变同化"),
  drill(17, "Learning", "What you learn from an experience depends partly on how carefully you reflect on it. Did you understand why a particular strategy succeeded or failed? Could you apply the same principle to a different problem? Such questions encourage learners to become more independent.", "what you / did you / could you / encourage learners", "音变同化"),
  drill(18, "Consumer Behaviour", "The products that you choose are influenced by many factors, including price, quality, advertising, and personal preference. Would you purchase an unfamiliar product simply because it was cheaper? Understanding such decisions allows researchers to examine how consumers respond to changing market conditions.", "that you / would you / because it / such decisions", "音变同化"),
  drill(19, "Social Communication", "Modern communication allows people to exchange ideas almost instantly. However, the message that you send may not always be interpreted in the way that you intended. Could you communicate the same idea more clearly by choosing different words or providing additional context?", "that you / that you intended / could you / different words", "音变同化"),
  drill(20, "Critical Thinking", "Critical thinking requires students to question the information they receive. Did you consider the reliability of the source? Would you reach the same conclusion if different evidence were available? Questions like these encourage individuals to evaluate claims rather than simply accepting them.", "did you / would you / different evidence / encourage individuals", "音变同化"),
  drill(21, "Three Significant Factors", "Three significant factors influence the growth of international trade: technological development, transportation costs, and government regulation. Although these factors vary considerably between countries, researchers generally agree that efficient infrastructure strengthens a nation's ability to participate successfully in the global economy.", "three / significant / factors / growth / technological / transportation / strengthens / successfully", "辅音组合"),
  drill(22, "Rural Communities", "Rural communities frequently rely on regional transport networks to reach essential services. Reliable roads and railways allow residents to travel regularly between smaller towns and larger urban centres. Poor infrastructure, however, can restrict economic growth and reduce employment opportunities throughout the region.", "rural / regularly / reliable / roads / railways / residents / restrict / throughout", "辅音组合"),
  drill(23, "Global Growth", "Global economic growth varies considerably across different regions. Governments generally attempt to create favourable conditions for investment while protecting vulnerable communities from sudden economic changes. Achieving both objectives requires careful regulation and long-term planning.", "global / growth / varies / favourable / vulnerable / regulation / long-term", "辅音组合"),
  drill(24, "Statistical Analysis", "Statistical analysis allows researchers to distinguish meaningful relationships from random variation. Nevertheless, statistical significance should not automatically be interpreted as practical importance. Researchers must carefully evaluate the strength of the evidence before reaching conclusions.", "statistical / analysis / researchers / distinguish / relationships / statistical significance / strength", "辅音组合"),
  drill(25, "Sustainable Strategies", "Successful sustainability strategies require strong cooperation between governments, businesses, and local communities. Strategies that appear effective in one region may be less suitable in another. Researchers must therefore consider social, environmental, and economic circumstances when recommending long-term solutions.", "successful sustainability strategies / strong / businesses / circumstances / solutions", "辅音组合"),
  drill(26, "Artificial Intelligence and Employment", "The increasing use of artificial intelligence has created considerable debate about the future of employment. Although automated systems can perform repetitive tasks efficiently, the introduction of new technology may also generate entirely new occupations. The overall effect will depend on how rapidly workers and organisations adapt to changing economic conditions.", "the + vowel / linking / weak forms / consonant clusters", "综合训练"),
  drill(27, "University Education", "The experience of university education extends beyond the acquisition of academic knowledge. Students are expected to interact with individuals from different backgrounds, evaluate unfamiliar ideas, and develop independent approaches to learning. These experiences can eventually influence both professional development and personal growth.", "the experience / the acquisition / interact_with / different backgrounds / develop_independent / these experiences", "综合训练"),
  drill(28, "Environmental Economics", "Economic development and environmental protection are sometimes presented as competing objectives. However, investment in efficient technology can reduce energy consumption while also lowering production costs. The challenge is to identify policies that encourage innovation without creating unnecessary economic burdens.", "development_and / investment_in / efficient / reduce_energy / the challenge / encourage_innovation / without creating", "综合训练"),
  drill(29, "Medical Research", "Advances in medical research have improved the diagnosis and treatment of many diseases. The introduction of advanced imaging technologies, for example, allows doctors to identify abnormalities at an earlier stage. Nevertheless, the effective use of such technology depends on accurate interpretation and appropriate clinical judgement.", "advances_in / the introduction / advanced_imaging / identify_abnormalities / at_an / the effective / accurate_interpretation", "综合训练"),
  drill(30, "Comprehensive Challenge", "The extraordinary expansion of international communication has transformed the exchange of information across the world. Individuals can now access enormous amounts of online material almost instantly, but the availability of information does not necessarily guarantee its accuracy. Effective communication therefore requires users to evaluate evidence carefully, distinguish reliable sources from misleading ones, and understand the broader context in which information is produced.", "comprehensive connected speech", "综合训练"),
];

export const RA_PRONUNCIATION_DRILL_IDS = RA_PRONUNCIATION_DRILLS.map((question) => question.id);

export function getRaPronunciationDrill(id: string) {
  return RA_PRONUNCIATION_DRILLS.find((question) => question.id === id) ?? null;
}
