import { NextRequest } from "next/server";
import { PDFDocument, StandardFonts, rgb, degrees, PDFFont } from "pdf-lib";
import { requireUser } from "@/lib/auth/require-user";

type SpeakingPart1Question = {
    id: number;
    topic_title: string;
    question_number: number;
    question_text: string;
    answer_text: string;
};

type SpeakingPart2Topic = {
    id: number;
    chinese_title: string | null;
    english_title: string | null;
    part2_question: string | null;
    cue_card_1: string | null;
    cue_card_2: string | null;
    cue_card_3: string | null;
    cue_card_4: string | null;
    part3_q1: string | null;
    part3_q2: string | null;
    part3_q3: string | null;
    part3_q4: string | null;
    part3_q5: string | null;
    part3_q6: string | null;
    part3_q7: string | null;
    part3_q8: string | null;
    part3_q9: string | null;
    part3_q10: string | null;
    category: string | null;
    difficulty: string | null;
    status: string | null;
    sort_order: number | null;
};

type ExportPayload =
    | {
        part: "all";
    }
    | {
        part: "part1";
        topic: string;
    }
    | {
        part: "part2";
        category: string;
    };

const PART1_COLUMNS = "id, topic_title, question_number, question_text, answer_text";
const PART2_COLUMNS = "id, chinese_title, english_title, part2_question, cue_card_1, cue_card_2, cue_card_3, cue_card_4, part3_q1, part3_q2, part3_q3, part3_q4, part3_q5, part3_q6, part3_q7, part3_q8, part3_q9, part3_q10, category, difficulty, status, sort_order";
const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const MARGIN_X = 50;
const MARGIN_TOP = 60;
const MARGIN_BOTTOM = 50;

const BODY_SIZE = 11;
const SMALL_SIZE = 9;
const TITLE_SIZE = 20;
const SUBTITLE_SIZE = 13;

// 行距稍微收窄
const LINE_GAP = 4;

function sanitizeFilename(value: string) {
    return value
        .trim()
        .toLowerCase()
        .replace(/[^\w\u4e00-\u9fff-]+/g, "-")
        .replace(/-+/g, "-")
        .replace(/^-|-$/g, "");
}

// 先让 Helvetica 安全输出，避免默认字体遇到中文或特殊符号时报错
function safePdfText(text: string | null | undefined) {
    if (!text) return "";
    return text
        .replace(/[•]/g, "-")
        .replace(/[\u2018\u2019]/g, "'")
        .replace(/[\u201C\u201D]/g, '"')
        .replace(/[\u2013\u2014]/g, "-")
        .replace(/\u00A0/g, " ")
        .replace(/[^\x09\x0A\x0D\x20-\x7E]/g, "");
}

function wrapText(
    text: string,
    maxWidth: number,
    font: PDFFont,
    fontSize: number
): string[] {
    const cleaned = safePdfText(text);
    const paragraphs = cleaned.split("\n");
    const lines: string[] = [];

    for (const paragraph of paragraphs) {
        const p = paragraph.trim();

        if (!p) {
            lines.push("");
            continue;
        }

        const words = p.split(/\s+/);
        let current = "";

        for (const word of words) {
            const candidate = current ? `${current} ${word}` : word;
            const width = font.widthOfTextAtSize(candidate, fontSize);

            if (width <= maxWidth) {
                current = candidate;
            } else {
                if (current) lines.push(current);

                if (font.widthOfTextAtSize(word, fontSize) <= maxWidth) {
                    current = word;
                } else {
                    let chunk = "";

                    for (const ch of word) {
                        const test = chunk + ch;
                        if (font.widthOfTextAtSize(test, fontSize) <= maxWidth) {
                            chunk = test;
                        } else {
                            if (chunk) lines.push(chunk);
                            chunk = ch;
                        }
                    }

                    current = chunk;
                }
            }
        }

        if (current) lines.push(current);
    }

    return lines;
}

function toPdfResponseBuffer(bytes: Uint8Array) {
    return bytes.buffer.slice(
        bytes.byteOffset,
        bytes.byteOffset + bytes.byteLength
    ) as ArrayBuffer;
}

function addWatermarkAndFooter(
    pdfDoc: PDFDocument,
    font: PDFFont,
    boldFont: PDFFont
) {
    const pages = pdfDoc.getPages();
    const totalPages = pages.length;

    pages.forEach((page, index) => {
        const { width, height } = page.getSize();

        // 斜着的大水印
        page.drawText("LOFTY EDUCATION", {
            x: width / 2 - 200,
            y: height / 2 - 170,
            size: 58,
            font: boldFont,
            color: rgb(0.85, 0.85, 0.85),
            rotate: degrees(45),
            opacity: 0.18,
        });

        // 左下角作者信息
        page.drawText("Generated by Chi", {
            x: 40,
            y: 20,
            size: 9,
            font,
            color: rgb(0.55, 0.55, 0.55),
        });

        // 右下角页码
        const pageLabel = `Page ${index + 1} of ${totalPages}`;
        const pageLabelWidth = font.widthOfTextAtSize(pageLabel, 9);

        page.drawText(pageLabel, {
            x: width - 40 - pageLabelWidth,
            y: 20,
            size: 9,
            font,
            color: rgb(0.55, 0.55, 0.55),
        });
    });
}

export async function POST(req: NextRequest) {
    try {
        const payload = (await req.json()) as ExportPayload;
        const { supabase } = await requireUser("/ielts/speaking");

        const pdfDoc = await PDFDocument.create();
        const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
        const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

        let page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
        let y = PAGE_HEIGHT - MARGIN_TOP;

        const contentWidth = PAGE_WIDTH - MARGIN_X * 2;

        const ensureSpace = (neededHeight: number) => {
            if (y - neededHeight < MARGIN_BOTTOM) {
                page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
                y = PAGE_HEIGHT - MARGIN_TOP;
            }
        };

        const drawLine = (
            text: string,
            opts?: {
                size?: number;
                bold?: boolean;
                color?: [number, number, number];
            }
        ) => {
            const size = opts?.size ?? BODY_SIZE;
            const usedFont = opts?.bold ? boldFont : font;
            const color = opts?.color ?? [0, 0, 0];
            const lines = wrapText(text, contentWidth, usedFont, size);

            for (const line of lines) {
                ensureSpace(size + LINE_GAP);

                page.drawText(line || " ", {
                    x: MARGIN_X,
                    y,
                    size,
                    font: usedFont,
                    color: rgb(color[0], color[1], color[2]),
                });

                y -= size + LINE_GAP;
            }
        };

        const addGap = (amount = 8) => {
            y -= amount;
        };

        const addPageBreak = () => {
            page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
            y = PAGE_HEIGHT - MARGIN_TOP;
        };

        if (payload.part === "all") {
            const [part1Result, part2Result] = await Promise.all([
                supabase
                    .schema("ielts")
                    .from("ielts_speaking_part1_questions")
                    .select(PART1_COLUMNS)
                    .order("topic_title", { ascending: true })
                    .order("question_number", { ascending: true }),
                supabase
                    .schema("ielts")
                    .from("ielts_speaking_part2_3")
                    .select(PART2_COLUMNS)
                    .eq("status", "published")
                    .order("sort_order", { ascending: true }),
            ]);

            if (part1Result.error) {
                console.error("IELTS speaking export Part 1 error:", part1Result.error);
                return new Response("Failed to load Part 1 data.", { status: 500 });
            }

            if (part2Result.error) {
                console.error("IELTS speaking export Part 2/3 error:", part2Result.error);
                return new Response("Failed to load Part 2/3 data.", { status: 500 });
            }

            const part1Items = (part1Result.data ?? []) as SpeakingPart1Question[];
            const part2Items = (part2Result.data ?? []) as SpeakingPart2Topic[];

            drawLine("IELTS Speaking Question Bank", { size: TITLE_SIZE, bold: true });
            drawLine("Part 1 + Part 2 / 3", { size: SUBTITLE_SIZE });
            drawLine(`Total questions/cards: ${part1Items.length + part2Items.length}`, { size: SMALL_SIZE });
            addGap(14);

            drawLine("Part 1", { size: TITLE_SIZE, bold: true });
            addGap(6);

            let currentTopic = "";

            for (const item of part1Items) {
                const safeTopic = safePdfText(item.topic_title);

                if (safeTopic !== currentTopic) {
                    currentTopic = safeTopic;
                    addGap(4);
                    drawLine(currentTopic || "Untitled Topic", { size: SUBTITLE_SIZE, bold: true });
                    addGap(2);
                }

                drawLine(`Question ${item.question_number}`, { size: SMALL_SIZE, bold: true, color: [0.35, 0.35, 0.35] });
                drawLine(item.question_text || "", { bold: true });
                addGap(1);
                drawLine(item.answer_text || "");
                addGap(8);
            }

            addPageBreak();
            drawLine("Part 2 / 3", { size: TITLE_SIZE, bold: true });
            addGap(8);

            for (let index = 0; index < part2Items.length; index++) {
                const item = part2Items[index];
                const cueCards = [item.cue_card_1, item.cue_card_2, item.cue_card_3, item.cue_card_4].filter(Boolean) as string[];
                const part3Questions = [item.part3_q1, item.part3_q2, item.part3_q3, item.part3_q4, item.part3_q5, item.part3_q6, item.part3_q7, item.part3_q8, item.part3_q9, item.part3_q10].filter(Boolean) as string[];

                drawLine(`${index + 1}. ${safePdfText(item.english_title || item.part2_question || "Untitled")}`, { size: SUBTITLE_SIZE, bold: true });

                if (item.category) {
                    drawLine(`Category: ${safePdfText(item.category)}`, { size: SMALL_SIZE });
                }

                if (item.difficulty) {
                    drawLine(`Difficulty: ${safePdfText(item.difficulty)}`, { size: SMALL_SIZE });
                }

                addGap(3);

                if (item.part2_question) {
                    drawLine("Part 2 Question", { size: SMALL_SIZE, bold: true });
                    drawLine(item.part2_question);
                    addGap(5);
                }

                if (cueCards.length > 0) {
                    drawLine("You should say:", { size: SMALL_SIZE, bold: true });
                    cueCards.forEach((cue) => drawLine(`- ${cue}`));
                    addGap(5);
                }

                if (part3Questions.length > 0) {
                    drawLine("Part 3 Discussion", { size: SMALL_SIZE, bold: true });
                    part3Questions.forEach((q, idx) => drawLine(`Q${idx + 1}. ${q}`));
                }

                addGap(10);
            }

            addWatermarkAndFooter(pdfDoc, font, boldFont);

            const pdfBytes = await pdfDoc.save();
            const pdfBuffer = toPdfResponseBuffer(pdfBytes);

            return new Response(pdfBuffer, {
                status: 200,
                headers: {
                    "Content-Type": "application/pdf",
                    "Content-Disposition": "attachment; filename=\"ielts-speaking-all.pdf\"",
                },
            });
        }

        if (payload.part === "part1") {
            let query = supabase
                .schema("ielts")
                .from("ielts_speaking_part1_questions")
                .select(PART1_COLUMNS)
                .order("topic_title", { ascending: true })
                .order("question_number", { ascending: true });

            if (payload.topic !== "All") {
                query = query.eq("topic_title", payload.topic);
            }

            const { data, error } = await query;

            if (error) {
                console.error("IELTS speaking export Part 1 error:", error);
                return new Response("Failed to load Part 1 data.", {
                    status: 500,
                });
            }

            const items = (data ?? []) as SpeakingPart1Question[];

            drawLine("IELTS Speaking Part 1", { size: TITLE_SIZE, bold: true });
            drawLine(`Topic: ${safePdfText(payload.topic) || "All"}`, {
                size: SUBTITLE_SIZE,
            });
            drawLine(`Total questions: ${items.length}`, { size: SMALL_SIZE });
            addGap(12);

            let currentTopic = "";

            for (const item of items) {
                const safeTopic = safePdfText(item.topic_title);

                if (safeTopic !== currentTopic) {
                    currentTopic = safeTopic;
                    addGap(4);
                    drawLine(currentTopic || "Untitled Topic", {
                        size: SUBTITLE_SIZE,
                        bold: true,
                    });
                    addGap(2);
                }

                drawLine(`Question ${item.question_number}`, {
                    size: SMALL_SIZE,
                    bold: true,
                    color: [0.35, 0.35, 0.35],
                });

                drawLine(item.question_text || "", { bold: true });
                addGap(1);
                drawLine(item.answer_text || "");
                addGap(8);
            }

            addWatermarkAndFooter(pdfDoc, font, boldFont);

            const pdfBytes = await pdfDoc.save();
            const pdfBuffer = toPdfResponseBuffer(pdfBytes);
            const filename = `speaking-part1-${sanitizeFilename(payload.topic || "all")}.pdf`;

            return new Response(pdfBuffer, {
                status: 200,
                headers: {
                    "Content-Type": "application/pdf",
                    "Content-Disposition": `attachment; filename="${filename}"`,
                },
            });
        }

        let query = supabase
            .schema("ielts")
            .from("ielts_speaking_part2_3")
            .select(PART2_COLUMNS)
            .eq("status", "published")
            .order("sort_order", { ascending: true });

        if (payload.category !== "All") {
            query = query.eq("category", payload.category);
        }

        const { data, error } = await query;

        if (error) {
            console.error("IELTS speaking export Part 2/3 error:", error);
            return new Response("Failed to load Part 2/3 data.", {
                status: 500,
            });
        }

        const items = (data ?? []) as SpeakingPart2Topic[];

        drawLine("IELTS Speaking Part 2 / 3", { size: TITLE_SIZE, bold: true });
        drawLine(`Category: ${safePdfText(payload.category) || "All"}`, {
            size: SUBTITLE_SIZE,
        });
        drawLine(`Total cards: ${items.length}`, { size: SMALL_SIZE });
        addGap(12);

        for (let index = 0; index < items.length; index++) {
            const item = items[index];

            const cueCards = [
                item.cue_card_1,
                item.cue_card_2,
                item.cue_card_3,
                item.cue_card_4,
            ].filter(Boolean) as string[];

            const part3Questions = [
                item.part3_q1,
                item.part3_q2,
                item.part3_q3,
                item.part3_q4,
                item.part3_q5,
                item.part3_q6,
                item.part3_q7,
                item.part3_q8,
                item.part3_q9,
                item.part3_q10,
            ].filter(Boolean) as string[];

            drawLine(
                `${index + 1}. ${safePdfText(
                    item.english_title || item.part2_question || "Untitled"
                )}`,
                {
                    size: SUBTITLE_SIZE,
                    bold: true,
                }
            );

            if (item.category) {
                drawLine(`Category: ${safePdfText(item.category)}`, {
                    size: SMALL_SIZE,
                });
            }

            if (item.difficulty) {
                drawLine(`Difficulty: ${safePdfText(item.difficulty)}`, {
                    size: SMALL_SIZE,
                });
            }

            addGap(3);

            if (item.part2_question) {
                drawLine("Part 2 Question", { size: SMALL_SIZE, bold: true });
                drawLine(item.part2_question);
                addGap(5);
            }

            if (cueCards.length > 0) {
                drawLine("You should say:", { size: SMALL_SIZE, bold: true });
                cueCards.forEach((cue) => drawLine(`- ${cue}`));
                addGap(5);
            }

            if (part3Questions.length > 0) {
                drawLine("Part 3 Discussion", { size: SMALL_SIZE, bold: true });
                part3Questions.forEach((q, idx) => drawLine(`Q${idx + 1}. ${q}`));
            }

            addGap(10);
        }

        addWatermarkAndFooter(pdfDoc, font, boldFont);

        const pdfBytes = await pdfDoc.save();
        const pdfBuffer = toPdfResponseBuffer(pdfBytes);
        const filename = `speaking-part2-3-${sanitizeFilename(payload.category || "all")}.pdf`;

        return new Response(pdfBuffer, {
            status: 200,
            headers: {
                "Content-Type": "application/pdf",
                "Content-Disposition": `attachment; filename="${filename}"`,
            },
        });
    } catch (error) {
        console.error("Speaking PDF export error:", error);
        return new Response("Failed to export PDF", { status: 500 });
    }
}
